/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialeRouteImport } from './routes/sociale'
import { Route as EventiRouteImport } from './routes/eventi'
import { Route as EnRouteImport } from './routes/en'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventiSlugRouteImport } from './routes/eventi.$slug'
import { Route as EnEventsRouteImport } from './routes/en.events'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnCharityRouteImport } from './routes/en.charity'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as EnEventsSlugRouteImport } from './routes/en.events.$slug'

const SocialeRoute = SocialeRouteImport.update({
  id: '/sociale',
  path: '/sociale',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiRoute = EventiRouteImport.update({
  id: '/eventi',
  path: '/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiSlugRoute = EventiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventiRoute,
} as any)
const EnEventsRoute = EnEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnCharityRoute = EnCharityRouteImport.update({
  id: '/charity',
  path: '/charity',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const EnEventsSlugRoute = EnEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/en': typeof EnRouteWithChildren
  '/eventi': typeof EventiRouteWithChildren
  '/sociale': typeof SocialeRoute
  '/en/about': typeof EnAboutRoute
  '/en/charity': typeof EnCharityRoute
  '/en/contact': typeof EnContactRoute
  '/en/events': typeof EnEventsRouteWithChildren
  '/eventi/$slug': typeof EventiSlugRoute
  '/en/events/$slug': typeof EnEventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/en': typeof EnRouteWithChildren
  '/eventi': typeof EventiRouteWithChildren
  '/sociale': typeof SocialeRoute
  '/en/about': typeof EnAboutRoute
  '/en/charity': typeof EnCharityRoute
  '/en/contact': typeof EnContactRoute
  '/en/events': typeof EnEventsRouteWithChildren
  '/eventi/$slug': typeof EventiSlugRoute
  '/en/events/$slug': typeof EnEventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/en': typeof EnRouteWithChildren
  '/eventi': typeof EventiRouteWithChildren
  '/sociale': typeof SocialeRoute
  '/en/about': typeof EnAboutRoute
  '/en/charity': typeof EnCharityRoute
  '/en/contact': typeof EnContactRoute
  '/en/events': typeof EnEventsRouteWithChildren
  '/eventi/$slug': typeof EventiSlugRoute
  '/en/events/$slug': typeof EnEventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/en'
    | '/eventi'
    | '/sociale'
    | '/en/about'
    | '/en/charity'
    | '/en/contact'
    | '/en/events'
    | '/eventi/$slug'
    | '/en/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/en'
    | '/eventi'
    | '/sociale'
    | '/en/about'
    | '/en/charity'
    | '/en/contact'
    | '/en/events'
    | '/eventi/$slug'
    | '/en/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/en'
    | '/eventi'
    | '/sociale'
    | '/en/about'
    | '/en/charity'
    | '/en/contact'
    | '/en/events'
    | '/eventi/$slug'
    | '/en/events/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  EnRoute: typeof EnRouteWithChildren
  EventiRoute: typeof EventiRouteWithChildren
  SocialeRoute: typeof SocialeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sociale': {
      id: '/sociale'
      path: '/sociale'
      fullPath: '/sociale'
      preLoaderRoute: typeof SocialeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi': {
      id: '/eventi'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi/$slug': {
      id: '/eventi/$slug'
      path: '/$slug'
      fullPath: '/eventi/$slug'
      preLoaderRoute: typeof EventiSlugRouteImport
      parentRoute: typeof EventiRoute
    }
    '/en/events': {
      id: '/en/events'
      path: '/events'
      fullPath: '/en/events'
      preLoaderRoute: typeof EnEventsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/charity': {
      id: '/en/charity'
      path: '/charity'
      fullPath: '/en/charity'
      preLoaderRoute: typeof EnCharityRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/events/$slug': {
      id: '/en/events/$slug'
      path: '/$slug'
      fullPath: '/en/events/$slug'
      preLoaderRoute: typeof EnEventsSlugRouteImport
      parentRoute: typeof EnEventsRoute
    }
  }
}

interface EnEventsRouteChildren {
  EnEventsSlugRoute: typeof EnEventsSlugRoute
}

const EnEventsRouteChildren: EnEventsRouteChildren = {
  EnEventsSlugRoute: EnEventsSlugRoute,
}

const EnEventsRouteWithChildren = EnEventsRoute._addFileChildren(
  EnEventsRouteChildren,
)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnCharityRoute: typeof EnCharityRoute
  EnContactRoute: typeof EnContactRoute
  EnEventsRoute: typeof EnEventsRouteWithChildren
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnCharityRoute: EnCharityRoute,
  EnContactRoute: EnContactRoute,
  EnEventsRoute: EnEventsRouteWithChildren,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface EventiRouteChildren {
  EventiSlugRoute: typeof EventiSlugRoute
}

const EventiRouteChildren: EventiRouteChildren = {
  EventiSlugRoute: EventiSlugRoute,
}

const EventiRouteWithChildren =
  EventiRoute._addFileChildren(EventiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  EnRoute: EnRouteWithChildren,
  EventiRoute: EventiRouteWithChildren,
  SocialeRoute: SocialeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
