/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialeRouteImport } from './routes/sociale'
import { Route as EventiRouteImport } from './routes/eventi'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventiRouteImport } from './routes/eventi.'

const SocialeRoute = SocialeRouteImport.update({
  id: '/sociale',
  path: '/sociale',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiRoute = EventiRouteImport.update({
  id: '/eventi',
  path: '/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiRoute = EventiRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/eventi': typeof EventiRouteWithChildren
  '/sociale': typeof SocialeRoute
  '/eventi/': typeof EventiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/sociale': typeof SocialeRoute
  '/eventi': typeof EventiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/eventi': typeof EventiRouteWithChildren
  '/sociale': typeof SocialeRoute
  '/eventi/': typeof EventiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/eventi'
    | '/sociale'
    | '/eventi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chi-siamo' | '/contatti' | '/sociale' | '/eventi'
  id:
    | '__root__'
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/eventi'
    | '/sociale'
    | '/eventi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  EventiRoute: typeof EventiRouteWithChildren
  SocialeRoute: typeof SocialeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sociale': {
      id: '/sociale'
      path: '/sociale'
      fullPath: '/sociale'
      preLoaderRoute: typeof SocialeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi': {
      id: '/eventi'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi/': {
      id: '/eventi/'
      path: '/'
      fullPath: '/eventi/'
      preLoaderRoute: typeof EventiRouteImport
      parentRoute: typeof EventiRoute
    }
  }
}

interface EventiRouteChildren {
  EventiRoute: typeof EventiRoute
}

const EventiRouteChildren: EventiRouteChildren = {
  EventiRoute: EventiRoute,
}

const EventiRouteWithChildren =
  EventiRoute._addFileChildren(EventiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  EventiRoute: EventiRouteWithChildren,
  SocialeRoute: SocialeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
